version: 2.1

# Define un flujo de trabajo llamado "build-test-deploy"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build

# Define el trabajo de construcción "build"
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build project
          command: ./gradlew build
